source 'https://github.com/CocoaPods/Specs.git'

target 'SGVInstanceSwizzling', :exclusive => true do
  pod "SGVInstanceSwizzling", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "SGVInstanceSwizzling", :path => "../"

  
end
